# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Developers Italia
description: Sviluppiamo i servizi pubblici, insieme
author: Dipartimento per la Trasformazione Digitale e AgID
twitter:
  username: developersITA

email: teamdigitale@governo.it
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://developers.italia.it"
twitter_username: developersITA
github_username:  italia
webanalytics_italia: jg7pYvEqvM

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-toc
  - jekyll-sitemap
  - searchyll
  - liquid-nested-sort
exclude:
  - .circleci
  - assets
  - AUTHORS
  - docker-compose.yml
  - Dockerfile
  - docs
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - Makefile
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - scripts
  - vendor

keep_files:
  # Have Jekyll not remove these directories when generating _site because
  # webpack writes its output there.
  - dist
  - assets

pagination:
  enabled: true
  debug: true
  per_page: 20
  sort_reverse: true
  title: ':title'

# tag pages
tag_page_layout: posts_by_tag
tag_page_dir: it/news
tag_page_data:
  langs:
    - it
    - en

# Atom feed configuration.
feed:
  limit: 10 # Number of posts for each feed.
  icon: /assets/icons/favicon.ico
  logo: /assets/icons/logo-it.svg

# Custom vars
theme_color: "#0066cc"
css_theme: t-Pac
owner_short: DTD
owner_full: Dipartimento per la Trasformazione Digitale
owner_link: https://innovazione.gov.it/dipartimento/
logo: /assets/icons/logo-it.svg
owner_logo: /assets/icons/logo-mid-white.svg
partner_short: AgID
partner_link: https://www.agid.gov.it
privacy_link: /it/privacy-policy
gov_logo: /assets/images/governo.svg
partner_logo: /assets/images/agid-logo-bb.svg
pill: ""
url_lineeguidariuso: https://docs.italia.it/italia/developers-italia/lg-acquisizione-e-riuso-software-per-pa-docs/it/stabile/
url_lineeguidariuso_en: https://docs.italia.it/italia/developers-italia/gl-acquisition-and-reuse-software-for-pa-docs/en/stabile/
newsletterdata:
   options:
   # You can add extra custom fields to the newsletter registration form
   # extra_fields:
   #   subscriberType:
   #     'Pubblica amministrazione': 1
   #     'Studente': 2
   args:
     # Sendportal workspace id
     workspace_id: 1
     # Des+Dev tag in Sendportal
     tag_id: 7

collections:
   platforms:
     output: true
     permalink: /:path/

# Here we assign a "type" string to each page. This is needed for the search engine.
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      subnav: "subnav"
      type: page
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "platforms"
    values:
      toc: true
      layout: platform
      type: platform
  -
    scope:
      path: "_posts/it"
    values:
      permalink: "it/news/:year/:month/:day/:title"
      lang: "it"
      type: news
    dir: it/news

  - scope:
      path: "_posts/en"
    values:
      permalink: "en/news/:year/:month/:day/:title"
      lang: "en"
      type: news

# page_gen:
#   - index_files: false
#     name: slug
#     data: apis
#     template: api-details
#     defaults:
#       lang: it
#       type: api
#     dir: it/api
#     #filter_condition: "record['language'].include? 'it'"

#   - index_files: false
#     name: slug
#     data: apis
#     template: api-details
#     defaults:
#       lang: en
#       type: api
#     dir: en/api
#     #filter_condition: "record['language'].include? 'en'"

#   - index_files: false
#     name: id
#     data: crawler.software
#     template: software-details
#     defaults:
#       lang: it
#       title_suffix: 'Developers Italia'
#     dir: it/software
#     # filter_condition: "record['language'].include? 'it'"

#   - index_files: false
#     name: id
#     data: crawler.software
#     template: software-details
#     defaults:
#       lang: en
#       title_suffix: 'Developers Italia'
#     dir: en/software
#     # filter_condition: "record['language'].include? 'en'"

#   - index_files: false
#     name: ipa
#     title: entityName
#     data: crawler.amministrazioni
#     template: brand-pa
#     defaults:
#       lang: it
#     dir: it/pa
#     # filter_condition: "record['language'].include? 'it'"

#   - index_files: false
#     name: ipa
#     title: entityName
#     data: crawler.amministrazioni
#     template: brand-pa
#     defaults:
#       lang: en
#     dir: en/pa
#     # filter_condition: "record['language'].include? 'it'"

sass:
    load_paths:
      - _sass
      - node_modules
      - assets
    sass_dir: /

elasticsearch:
  url: ENV_ELASTICSEARCH_URL
  number_of_shards: 5
  number_of_replicas: 1
  index_name: "developers_italia_it"
  default_type: "_doc"
  custom_settings: _es_settings.yml
  custom_mappings: _es_mappings.yml
  ignore:
    # Already indexed in the 'publiccodes' index.
    - /it/software/*
    - /en/software/*

    # Already indexed in the 'administrations' index.
    - /it/pa/*
    - /en/pa/*
