# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Developers Italia
description: Sviluppiamo i servizi pubblici, insieme
author: Team Digitale e AgID
twitter:
  username: developersITA

email: teamdigitale@governo.it
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://developers.italia.it"
twitter_username: developersITA
github_username:  italia
#piwik: teamdigitale
google_analytics: UA-96140462-1

# Github importer
github_api_url: https://api.github.com
github_folder: github
github_projects_prefix: ['spid-', '18app', 'anpr-','daf-','dati-','pianotriennale-','lg-','design-','security-','cie-']
github_access_token: ENV_GITHUB_ACCESS_TOKEN
github_blacklist_repos: []
github_issues_types: ['bug','enhancement','new project']
github_tech_list: [
  'angular', 'react', 'design', 'html', 'arduino', 'bootstrap', 'frontend',
  'perl','python', 'cpp', 'scala', 'php', 'csharp', 'java', 'android', 'ios', 'dotnet',
  'wordpress', 'metabase', 'ansible', 'docker', 'magento', 'joomla', 'django']

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-toc
  - jekyll-sitemap
  - searchyll
exclude:
  - vendor
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - circle.yml
  - gulpfile.js
  - package.json
  - package-lock.json
  - yarn.lock
  - swagger/.cache
  - swagger/dist
  - swagger/node_modules


pagination:
  enabled: true
  debug: true
  per_page: 20
  sort_reverse: true

# tag pages
tag_page_layout: posts_by_tag
tag_page_dir: it/news
tag_page_data:
  langs:
    - it
    - en

# Custom vars
theme_color: "#0066cc"
css_theme: t-Pac
owner_short: AgID
owner_full: AgID
owner_link: http://www.agid.gov.it
logo: /assets/icons/logo-it.svg
owner_logo: /assets/images/agid-logo-bb.svg
partner_short: Team Digitale
partner_full: Team per la Trasformazione Digitale
partner_link: https://teamdigitale.governo.it
privacy_link: /it/privacy-policy
gov_logo: https://teamdigitale.governo.it/images/loghi/governo.svg
partner_logo: /assets/icons/dt-logo.svg #https://teamdigitale.governo.it/images/loghi/demo.png
pill: ""
url_lineeguidariuso: https://docs.italia.it/italia/developers-italia/lg-acquisizione-e-riuso-software-per-pa-docs/it/stabile/ 
url_lineeguidariuso_en: https://docs.italia.it/italia/developers-italia/gl-acquisition-and-reuse-software-for-pa-docs/en/stabile/
newsletterdata:
    placeholdertext: mario.rossi@devsoftware.it
    action: "https://a0x0b4.emailsp.com/frontend/subscribe.aspx"
    hidden-inputs:
        -
          name: list
          value: 1

collections:
   pages:
     output: true
     permalink: /:path/
     layout: page
   platforms:
     output: true
     permalink: /:path/

# Here we assign a "type" string to each page. This is needed for the search engine.
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      subnav: "subnav"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "platforms"
    values:
      toc: true
      layout: platform
      type: platform
  -
    scope:
      path: "_posts/it"
    values:
      permalink: "it/news/:year/:month/:day/:title"
      lang: "it"
      type: news
    dir: it/news

  - scope:
      path: "_posts/en"
    values:
      permalink: "en/news/:year/:month/:day/:title"
      lang: "en"
      type: news

page_gen:
  - index_files: false
    name: slug
    data: apis
    template: api-details
    defaults:
      type: api
    dir: it/api
    #filter_condition: "record['language'].include? 'it'"

  - index_files: false
    name: slug
    data: apis
    template: api-details
    defaults:
      type: api
    dir: en/api
    #filter_condition: "record['language'].include? 'en'"

  - index_files: false
    name: slug
    data: crawler.softwares
    template: software-details
    defaults:
      lang: it
      title_suffix: 'Developers Italia'
    dir: it/software
    # filter_condition: "record['language'].include? 'it'"

  - index_files: false
    name: slug
    data: crawler.softwares
    template: software-details
    defaults:
      lang: en
      title_suffix: 'Developers Italia'
    dir: en/software
    # filter_condition: "record['language'].include? 'en'"

sass:
    load_paths:
      - _sass
      - node_modules
      - assets
    sass_dir: /

elasticsearch:
  url: ENV_ELASTICSEARCH_URL
  number_of_shards: 5
  number_of_replicas: 1
  index_name: "jekyll"
  default_type: "post"
  custom_settings: _es_settings.yml
  custom_mappings: _es_mappings.yml
  ignore:
    - /it/software/*
    - /en/software/*
    - /it/bagnacavallo/
