# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Developers Italia
description: La comunit√† italiana degli sviluppatori di servizi pubblici
author: Team Digitale e AgID
twitter:
  username: developersITA

email: teamdigitale@governo.it
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://developers.italia.it"
twitter_username: developersITA
github_username:  italia
piwik: teamdigitale
google_analytics: UA-96140462-1

# Github importer
github_api_url: https://api.github.com
github_folder: github
github_projects_prefix: ['spid-', '18app', 'anpr-','daf-','dati-','pianotriennale-','lg-','design-','security-','cie-']
github_access_token: ENV_GITHUB_ACCESS_TOKEN
github_blacklist_repos: []
github_issues_types: ['bug','enhancement','new project']
github_tech_list: [
  'angular', 'react', 'design', 'html', 'arduino', 'bootstrap', 'frontend',
  'perl','python', 'cpp', 'scala', 'php', 'csharp', 'java', 'android', 'ios', 'dotnet',
  'wordpress', 'metabase', 'ansible', 'docker', 'magento', 'joomla', 'django']

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-toc
  - jekyll-sitemap
exclude:
  - vendor
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - circle.yml
  - gulpfile.js
  - package.json
  - yarn.lock
  - swagger/.cache
  - swagger/dist

paginate: 10
paginate_path: "/news/page:num/"

# tag pages
tag_page_layout: posts_by_tag
tag_page_dir: news

# Custom vars
theme_color: "#0066cc"
css_theme: t-Pac
owner_short: AgID
owner_full: AgID
owner_link: http://www.agid.gov.it
logo: /assets/icons/logo-it.png
owner_logo: https://www.spid.gov.it/assets/img/agid-logo-bb.svg
partner_short: Team Digitale
partner_full: Team per la Trasformazione Digitale
partner_link: https://teamdigitale.governo.it
privacy_link: https://developers.italia.it/it/privacy-policy
gov_logo: https://teamdigitale.governo.it/images/loghi/governo.svg
partner_logo: /assets/icons/dt-logo.svg #https://teamdigitale.governo.it/images/loghi/demo.png
pill: beta

collections:
   pages:
     output: true
     permalink: /:path/
     layout: page
   projects:
     output: true
     permalink: /:path/
     layout: project
   faqs:
     output: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      subnav: "subnav"
    scope:
      path: "" # an empty string here means all files in the project
      type: "projects"
    values:
      toc: true

page_gen:
  - index_files: false
    name: name
    data: apis
    template: api-details
    dir: it/api
    filter_condition: "record['language'].include? 'it'"

  - index_files: false
    name: name
    data: apis
    template: api-details
    dir: en/api
    filter_condition: "record['language'].include? 'en'"
