name: ðŸ”­ publiccode.yml crawl ðŸ”­

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * *'
jobs:
  crawl:
    runs-on: ubuntu-latest
    container:
      image: italia/publiccode-crawler:latest
    steps:
      - uses: actions/checkout@v3
      - run: publiccode-crawler crawl
        env:
          API_BASEURL: "https://api.developers.italia.it/v1"
          API_BEARER_TOKEN: ${{ secrets.API_BEARER_TOKEN }}

          # https://api.developers.italia.it/v1/publishers/456123fe-e5ad-41fa-b894-8a021a8ed972
          MAIN_PUBLISHER_ID: "456123fe-e5ad-41fa-b894-8a021a8ed972"

          SKIP_VITALITY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
